			{"axis_realistic" 
				{title "mp/alliance/axis_realistic"}
				{armies "ger"}
				{armies "ger2"}
				{armies "ger_ss"}
				{icon "/interface/pages/multi/flag_ger"}
			}
			{"allies_realistic"
				{title "mp/alliance/allies_realistic"}
				{armies "usa"}
				{armies "eng"}
				{armies "fra"}
				{icon "/interface/pages/multi/flag_allies_realistic"}
			}
			{"allies_pacific"
				{title "mp/alliance/allies_pacific"}
				{armies "usmc"}
				{icon "/interface/pages/multi/flag_usmc"}
			}
			{"allies_west"
				{title "mp/alliance/allies_west"}
				{armies "usa"}
				{armies "usmc"}
				{armies "eng"}
				{armies "fra"}
				{icon "/interface/pages/multi/flag_allies_west"}
			}
			{"allies_ussr"
				{title "mp/alliance/allies_ussr"}
				{armies "rus"}
				{armies "rus_guard"}
				{icon "/interface/pages/multi/flag_rus"}
			}
			{"axis_west" 
				{title "mp/alliance/axis_west"}
				{armies "ger"}
				{armies "ger_ss"}
				{icon "/interface/pages/multi/flag_ger"}
			}
			{"axis_jap" 
				{title "mp/alliance/axis_jap"}
				{armies "jap"}
				{icon "/interface/pages/multi/flag_jap"}
			}
			{"axis_ger" 
				{title "mp/alliance/axis_ger"}
				{armies "ger"}
				{icon "/interface/pages/multi/flag_ger"}
			}
			{"axis_ger2" 
				{title "mp/alliance/axis_ger2"}
				{armies "ger2"}
				{icon "/interface/pages/multi/flag_ger2"}
			}
			{"axis_ss" 
				{title "mp/alliance/axis_ss"}
				{armies "ger_ss"}
				{icon "/interface/pages/multi/flag_ger_ss"}
			}
			{"axis" 
				{title "mp/alliance/axis"}
				{armies "ger"}
				{armies "ger2"}
				{armies "jap"}
				{armies "ger_ss"}
				{armies "hun"}
				{icon "/interface/pages/multi/flag_axis"}
			}
			
			{"allies_rus"
				{title "mp/alliance/allies_rus"}
				{armies "rus"}
				{icon "/interface/pages/multi/flag_rus"}
			}
			{"allies_rus_guard"
				{title "mp/alliance/allies_rus_guard"}
				{armies "rus_guard"}
				{icon "/interface/pages/multi/flag_rus_guard"}
			}
			{"allies_usa"
				{title "mp/alliance/allies_usa"}
				{armies "usa"}
				{icon "/interface/pages/multi/flag_usa"}
			}
			{"allies_eng"
				{title "mp/alliance/allies_eng"}
				{armies "eng"}
				{icon "/interface/pages/multi/flag_eng"}
			}
			
			
			{"axis_ger-ger2" 
				{title "mp/alliance/axis_ger-ger2"}
				{armies "ger"}
				{armies "ger2"}
				{icon "/interface/pages/multi/flag_ger"}
			}
			
			{"axis_ss-ger2" 
				{title "mp/alliance/axis_ss-ger2"}
				{armies "ger_ss"}
				{armies "ger2"}
				{icon "/interface/pages/multi/flag_ger"}
			}
			{"allies_fra"
				{title "mp/alliance/allies_fra"}
				{armies "fra"}
				{icon "/interface/pages/multi/flag_fra"}
			}
			
			
			{"allies"
				{title "mp/alliance/allies"}
				{armies "usa"}
				{armies "usmc"}
				{armies "eng"}
				{armies "fra"}
				{armies "rus"}
				{armies "rus_guard"}
				{icon "/interface/pages/multi/flag_allies"}
			}
			