
;artillery doctrine
{"grenadiers_44(ger_doc_a)" "Grenadier squad"}
{"vehic_supporter(ger_doc_a)" "Support crew"}
{"officers(ger_doc_a)" "Officer"}
{"np_sdkfz8(a)" "Sd.Kfz.8"}
{"np_sdkfz251_4(a)" "Sd.Kfz.251/4 ammo carrier"}
{"blitz3_6art(a)" "Opel Blitz 3.6 Heavy ammo truck"}
{"ammo_box_ger_art(a)" "Heavy ammo crate"}
{"sgrw_34(a)" "8cm GrW 34"}
{"sgrw_42(a)" "12cm SGrW 42"}
{"75mm_leig18(a)" "Le.IG 18"}
{"15_cm_sig33(a)" "S.IG 33"}
{"flak18a(a)" "FlaK 18"}
{"lefh18(a)" "Le.FH 18"}
{"sfh18(a)" "S.FH 18"}
{"morser18(a)" "Morser 18"}
{"nebelwerfer41(a)" "15cm Nebelwerfer 41"}
{"nebelwerfer42(a)" "28/32cm Nebelwerfer 41"}
{"np_sdkfz251_1w(a)" "Sd.Kfz.251/1 'stuka zu fuss'"}
{"grille(a)" "Grille"}
{"wespe(a)" "Wespe"}
{"hummel(a)" "Hummel"}
{"sdkfz4(a)" "Sd.Kfz.4 Panzerwerfer"}

;armored defense doctrine
{"home_guards(ger_doc_ad)" "Volkssturm squad"}
{"volksgrens(ger_doc_ad)" "Volksgrenadier squad"}
{"grenadiers_44(ger_doc_ad)" "Grenadier squad"}
{"tankmans(ger_doc_ad)" "Tank crew"}
{"blitz3_6art(ad)" "Opel Blitz 3.6 Heavy ammo truck"}
{"np_sdkfz251_1(ad)" "Sd.Kfz.251/1"}
{"np_sdkfz250_7(ad)" "Sd.Kfz.250/7 mortar carrier"}
{"np_sdkfz251_9(ad)" "Sd.Kfz.251/9"}
{"np_sdkfz251_17(ad)" "Sd.Kfz.251/17"}
{"ostwind(ad)" "Flakpanzer IV Ostwind"}
{"pz4j(ad)" "Pz.Kpfw IV Ausf. J"}
{"elefant(ad)" "Panzerjager elefant"}

;ambush doctrine
{"jagers_44(ger_doc_am)" "Jager squad"}
{"gebirgsjager_44(ger_doc_am)" "Gebirgsjager squad"}
{"tankmans(ger_doc_am)" "Tank crew"}
{"vehic_supporter(ger_doc_am)" "Support crew"}
{"bazookers(ger_doc_am)" "Panzerschreck infantry"}
{"bazooker3(ger_doc_am)" "Panzerfaust infantry"}
{"blitz3_6art(am)" "Opel Blitz 3.6 Heavy ammo truck"}
{"ammo_box_ger_art(am)" "Heavy ammo crate"}
{"sdkfz303(am)" "Sd.Kfz.303 'Goliath'"}
{"pak38(am)" "5cm PaK 38"}
{"np_pak40(am)" "7.5cm PaK 40"}
{"pak43(am)" "8.8cm PaK 43"}
{"np_sdkfz250_10(am)" "Sd.Kfz.250/10"}
{"np_sdkfz251_10(am)" "Sd.Kfz.251/10"}
{"sdkfz234(am)" "Sd.Kfz.234 Puma"}
{"np_sdkfz234_4(am)" "Sd.Kfz.234/4 PaK 40"}
{"marder_3m(am)" "Marder III Ausf. M"}
{"hetzer(am)" "Panzerjager 38(t) Hetzer"}
{"nashorn(am)" "Panzerjager Nashorn"}

;breakthrough doctrine
{"volksgrens_heavy(ger_doc_bt)" "Heavy Volksgrenadier squad"}
{"sturmgrens_44(ger_doc_bt)" "Sturmgrenadier squad"}
{"grenadiers_elite(ger_doc_bt)" "Elite grenadier squad"}
{"grenadiers_elite_btr(ger_doc_bt)" "Elite Mechanized grenadier squad"}
{"tankmans(ger_doc_bt)" "Tank crew"}
{"officers(ger_doc_bt)" "Panzer Officer"}
{"blitz3_6(bt)" "Opel Blitz 3.6"}
{"blitz3_6art(bt)" "Opel Blitz 3.6 Heavy ammo truck"}
{"sdkfz251_1(bt)" "Sd.Kfz.251/1"}
{"np_sdkfz251_1w(bt)" "Sd.Kfz.251/1 'stuka zu fuss'"}
{"pz3_m_flamer(bt)" "Pz.Kpfw III Flammpanzer"}
{"pz4h(bt)" "Pz.Kpfw IV Ausf. H"}
{"pz6e(bt)" "Pz.Kpfw VI Tiger Ausf. E"}
{"pz6e_dual(bt)" "Dual Pz.Kpfw VI Tiger Ausf. E"}
{"sturmtiger(bt)" "Sturmtiger"}

;fortification doctrine
{"volksgrens(ger_doc_f)" "Volksgrenadier squad"}
{"grenadiers_44(ger_doc_f)" "Grenadier squad"}
{"fusiliers_44(ger_doc_f)" "Fusilier squad"}
{"ap_miners(ger_doc_f)" "AP mine infantry"}
{"at_miners(ger_doc_f)" "AT mine infantry"}
{"sappers(ger_doc_f)" "Mine disposal infantry"}
{"vehic_supporter(ger_doc_f)" "Support crew"}
{"at_rifles(ger_doc_f)" "AT rifle infantry"}
{"mg2(ger_doc_f)" "MG34 Grenadier"}
{"mg2_fusilier(ger_doc_f)" "MG34 Fusilier"}
{"steyr_rso(f)" "Steyr RSO"}
{"np_sdkfz8(f)" "Sd.Kfz.8"}
{"blitz3_6eng(f)" "Opel Blitz 3.6 Engineering truck"}
{"ammo_box_ger_inf(f)" "Infantry ammo crate"}
{"ammo_box_ger_art(f)" "Heavy ammo crate"}
{"ammo_box_ger_special(f)" "Special ammo crate"}
{"mg34_lafette(f)" "MG34 lafette tripod"}
{"mg42_lafette(f)" "MG42 lafette tripod"}
{"2cm_flak38(f)" "2cm FlaK 38"}
{"2cm_flak3vierling8(f)" "2cm Flakvierling 38"}
{"37mm_flak_36(f)" "3.7cm FlaK 36"}
{"5_cm_granatwerfer_36(f)" "5cm GrW 36"}
{"sgrw_34(f)" "8cm GrW 34"}
{"sgrw_42(f)" "12cm SGrW 42"}
{"flak36a(f)" "8.8cm FlaK 36"}
{"pak38(f)" "5cm PaK 38"}
{"np_pak40(f)" "7.5cm PaK 40"}
{"pak43(f)" "8.8cm PaK 43"}
{"pak44(f)" "12.8cm PaK 44"}

;heavy panzer doctrine
{"stormtroopers_44(ger_doc_hp)" "Panzergrenadier squad"}
{"stormtroopers_btr(ger_doc_hp)" "Mechanized Panzergrenadier squad"}
{"tankmans(ger_doc_hp)" "Tank crew"}
{"elite_tankmans(ger_doc_hp)" "Veteran Tank crew"}
{"officers(ger_doc_hp)" "Panzer Officer"}
{"kubel_mgun_34(hp)" "Kubelwagen MG34"}
{"blitz3_6art(hp)" "Opel Blitz 3.6 Heavy ammo truck"}
{"np_sdkfz251_1(hp)" "Sd.Kfz.251/1"}
{"np_sdkfz251_17(hp)" "Sd.Kfz.251/17"}
{"pz6e(hp)" "Pz.Kpfw VI Tiger Ausf. E"}
{"pz6e_dual(hp)" "Dual Pz.Kpfw VI Tiger Ausf. E"}
{"veteran_tiger(hp)" "Pz.Kpfw VI Tiger Ausf. E 'Veteran'"}
{"sdkfz182b(hp)" "Pz.Kpfw VI Tiger Ausf. B Early turret"}
{"pz6bh(hp)" "Pz.Kpfw VI Tiger Ausf. B Production turret"}
{"pz6bh_dual(hp)" "Dual Pz.Kpfw VI Tiger Ausf. B Production turret"}

;infantry doctrine
{"volksgrens(ger_doc_i)" "Volksgrenadier squad"}
{"volksgrens_sturm(ger_doc_i)" "Volksgrenadier Sturm squad"}
{"volksgrens_heavy(ger_doc_i)" "Heavy Volksgrenadier squad"}
{"sturmgrens_44(ger_doc_i)" "Sturmgrenadier squad"}
{"grenadiers_44(ger_doc_i)" "Grenadier squad"}
{"jagers_44(ger_doc_i)" "Jager squad"}
{"stormtroopers_44(ger_doc_i)" "Panzergrenadier squad"}
{"grenadiers_elite(ger_doc_i)" "Elite Grenadier squad"}
{"gebirgsjager_44(ger_doc_i)" "Gebirgsjager squad"}
{"vehic_supporter(ger_doc_i)" "Support crew"}
{"at_rifles(ger_doc_i)" "AT rifle infantry"}
{"bazookers(ger_doc_i)" "Panzerschreck infantry"}
{"bazooker3(ger_doc_i)" "Panzerfaust infantry"}
{"snipers(ger_doc_i)" "Scharfschutze"}
{"sniper3(ger_doc_i)" "Scharfschutze"}
{"sniper2(ger_doc_i)" "Veteran Scharfschutze"}
{"officers(ger_doc_i)" "Officer"}
{"r12_34(i)" "BMW R12 'MG34'"}
{"r12(i)" "BMW R12 'MG42'"}
{"kubel_mgun_34(i)" "Kubelwagen 'MG34'"}
{"kubel_mgun(i)" "Kubelwagen 'MG42'"}
{"np_sdkfz251_1(i)" "Sd.Kfz.251/1"}
{"sdkfz251_1(i)" "Sd.Kfz.251/1"}
{"ammo_box_ger_inf(i)" "Infantry ammo crate"}
{"ammo_box_ger_art(i)" "Heavy ammo crate"}
{"mg34_lafette(i)" "MG34 lafette tripod"}
{"mg42_lafette(i)" "MG42 lafette tripod"}
{"5_cm_granatwerfer_36(i)" "5cm GrW 36"}
{"sgrw_34(i)" "8cm GrW 34"}
{"pak36(i)" "3.7cm PaK 36"}
{"pak38(i)" "5cm PaK 38"}

;luftwaffe doctrine
{"elites_44(ger_doc_luft)" "Fallschirmjager squad"}
{"elites_44_drop(ger_doc_luft)" "Paradropped Fallschirmjager squad"}
{"elites_44_special(ger_doc_luft)" "Fallschirmjager squad (special ability)"}
{"elites_44_drop_special(ger_doc_luft)" "Paradropped Fallschirmjager squad (special ability)"}
{"bazooker_fallschirm(ger_doc_luft)" "Fallschirmjager Panzerschreck infantry"}
{"sniper_fallschirm(ger_doc_luft)" "Fallschirmjager Scharfschutze"}
{"fallschirm_supporter(ger_doc_luft)" "Fallschirmjager support infantry"}
{"r12_34(luft)" "BMW R12 'MG34'"}
{"r12(luft)" "BMW R12 'MG42'"}
{"ammo_box_ger_inf(luft)" "Infantry ammo crate"}
{"ammo_box_ger_art(luft)" "Heavy ammo crate"}
{"mg34_lafette(luft)" "MG34 lafette tripod"}
{"mg42_lafette(luft)" "MG42 lafette tripod"}
{"sgrw_34(luft)" "8cm GrW 34"}
{"2cm_flak38(luft)" "2cm FlaK 38"}
{"75mm_leig18(luft)" "Le.IG 18"}
{"pak38(luft)" "5cm PaK 38"}
{"stuh42(luft)" "StuH 42"}
{"stug3g(luft)" "StuG III Ausf. G"}

;panzer doctrine
{"stormtroopers_44(ger_doc_p)" "Panzergrenadier squad"}
{"stormtroopers_btr(ger_doc_p)" "Mechanized Panzergrenadier squad"}
{"tankmans(ger_doc_p)" "Tank crew"}
{"officers(ger_doc_p)" "Panzer Officer"}
{"blitz3_6art(p)" "Opel Blitz 3.6 Heavy ammo truck"}
{"pz3j(p)" "PzKpfw III Ausf. J"}
{"pz3(p)" "PzKpfw III Ausf. J1"}
{"pz3_m(p)" "PzKpfw III Ausf. M"}
{"pz4g(p)" "PzKpfw IV Ausf. G"}
{"pz4g_dual(p)" "Dual PzKpfw IV Ausf. G"}
{"pz4h(p)" "PzKpfw IV Ausf. H"}
{"pz4h_dual(p)" "Dual PzKpfw IV Ausf. H"}
{"pz4j(p)" "PzKpfw IV Ausf. J"}
{"pz5a(p)" "PzKpfw V Panther Ausf. A"}
{"pz5g(p)" "PzKpfw V Panther Ausf. G"}

;panzerjager doctrine
{"volksgrens(ger_doc_pj)" "Volksgrenadier squad"}
{"grenadiers_44(ger_doc_pj)" "Grenadier squad"}
{"tankmans(ger_doc_pj)" "Tank crew"}
{"bazookers(ger_doc_pj)" "Panzerschreck infantry"}
{"bazooker3(ger_doc_pj)" "Panzerfaust infantry"}
{"blitz3_6art(pj)" "Opel Blitz 3.6 Heavy ammo truck"}
{"hetzer(pj)" "Jagdpanzer 38(t) Hetzer"}
{"jagdpanzer_iv_l48(pj)" "Jagdpanzer IV L/48"}
{"jagdpanzer_iv(pj)" "Jagdpanzer IV L/70"}
{"jagdpanther(pj)" "Jagdpanzer V Jagdpanther"}
{"jagdtiger(pj)" "Panzerjager Tiger Ausf. B 'Jagdtiger'"}

;panzersupport doctrine
{"stormtroopers_44(ger_doc_ps)" "Panzergrenadier squad"}
{"tankmans(ger_doc_ps)" "Tank crew"}
{"vehic_supporter(ger_doc_ps)" "Support crew"}
{"blitz3_6art(ps)" "Opel Blitz 3.6 Heavy ammo truck"}
{"np_sdkfz251_4(ps)" "Sd.Kfz.251/4 ammo carrier"}
{"np_sdkfz251_1(ps)" "Sd.Kfz.251/1"}
{"sdkfz251_1(ps)" "Sd.Kfz.251/1"}
{"75mm_leig18(ps)" "Le.IG 18"}
{"15_cm_sig33(ps)" "S.IG 33"}
{"grille(ps)" "Grille"}
{"brummbar(ps)" "Sturmpanzer IV 'Brummbar'"}
{"welberwind(ps)" "Flakpanzer IV Wirbelwind"}
{"pz3_m(ps)" "PzKpfw III Ausf. M"}
{"pz3n(ps)" "PzKpfw III Ausf. N"}
{"stug3g(ps)" "StuG III Ausf. G"}

;recon doctrine
{"recon(ger_doc_r)" "Aufklarung squad"}
{"recon_motor(ger_doc_r)" "Motorized Aufklarung squad"}
{"recon_mech(ger_doc_r)" "Mechanized Aufklarung squad"}
{"tankmans(ger_doc_r)" "Tank crew"}
{"vehic_supporter(ger_doc_r)" "Support crew"}
{"snipers(ger_doc_r)" "Scharfschutze"}
{"sniper3(ger_doc_r)" "Scharfschutze"}
{"radioman_mortar(ger_doc_r)" "Radioman mortar call-in"}
{"officers(ger_doc_r)" "Officer"}
{"r12(r)" "BMW R12 'MG42'"}
{"kubel_mgun(r)" "Kubelwagen 'MG42'"}
{"schwimmwagen(r)" "Schwimmwagen"}
{"blitz3_6(r)" "Opel Blitz 3.6"}
{"blitz3_6art(r)" "Opel Blitz 3.6 Heavy ammo truck"}
{"np_sdkfz250_1(r)" "Sd.Kfz.250/1"}
{"np_sdkfz251_1(r)" "Sd.Kfz.251/1"}
{"75mm_leig18(r)" "Le.IG 18"}
{"pak38(r)" "5cm PaK 38"}
{"np_pak40(r)" "7.5cm PaK 40"}
{"np_sdkfz250_10(r)" "Sd.Kfz.250/10"}
{"np_sdkfz250_9(r)" "Sd.Kfz.250/9"}
{"sdkfz223(r)" "Sd.Kfz.223"}
{"sdkfz222(r)" "Sd.Kfz.222"}
{"pz2l(r)" "PzKpfw II Luchs"}
{"np_sdkfz234_1(r)" "Sd.Kfz.234/1"}
{"sdkfz234(r)" "Sd.Kfz.234/2 Puma"}
{"np_sdkfz234_3(r)" "Sd.Kfz.234/3"}
{"np_sdkfz234_4(r)" "Sd.Kfz.234/4 PaK 40"}

;reserve troops doctrine
{"home_guards(ger_doc_rt)" "Volkssturm squad"}
{"volksgrens(ger_doc_rt)" "Volksgrenadier squad"}
{"sdkfz223(rt)" "Sd.Kfz.223"}
{"pzkpfw38t_b(rt)" "PzKpfw 38(t)"}
{"pz4e(rt)" "PzKpfw IV Ausf. E"}
{"pz5d(rt)" "PzKpfw V Panther Ausf. D"}
{"sdkfz182b(rt)" "PzKpfw VI Tiger Ausf. B 'Early turret'"}
{"stug3f(rt)" "StuG III Ausf. F"}
{"stug3f_8(rt)" "StuG III Ausf. F/8"}

;spearhead doctrine
{"stormtroopers_44(ger_doc_sh)" "Panzergrenadier squad"}
{"stormtroopers_btr(ger_doc_sh)" "Mechanized Panzergrenadier squad"}
{"tankmans(ger_doc_sh)" "Tank crew"}
{"elite_tankmans(ger_doc_sh)" "Veteran Tank crew"}
{"officers(ger_doc_sh)" "Panzer Officer"}
{"blitz3_6art(sh)" "Opel Blitz 3.6 Heavy ammo truck"}
{"sdkfz251_1(sh)" "Sd.Kfz.251/1"}
{"wespe(sh)" "Wespe"}
{"sdkfz4(sh)" "Sd.Kfz.4 'Panzerwerfer'"}
{"pz2l(sh)" "PzKpfw II Luchs"}
{"sdkfz234(sh)" "Sd.Kfz.234/2 Puma"}
{"stuh42(sh)" "StuH 42"}
{"stug3g(sh)" "StuG III Ausf. G"}
{"pz5g(sh)" "PzKpfw V Panther Ausf. G"}
{"pz5g_veteran(sh)" "PzKpfw V Panther Ausf. G 'Veteran'"}








