
;armor doctrine
{"riflemans(usa_doc_a)" "Armored Rifle squad"}
{"riflemans_btr(usa_doc_a)" "Mechanized Armored Rifle squad"}
{"tankmans(usa_doc_a)" "Tank crew"}
{"officers(usa_doc_a)" "Armor Officer"}
{"gmc_art(a)" "GMC CCKW Heavy ammo truck"}
{"m4a1(a)" "M4A1 sherman"}
{"m4sherman(a)" "M4 sherman"}
{"m4a3_75(a)" "M4A3 sherman"}
{"m4a1_76w(a)" "M4A1(76)W sherman"}
{"m4a3e8(a)" "M4A3E8(76)W sherman"}
{"armor_special(a)" "Sherman platoon"}

;artillery doctrine
{"riflemans(usa_doc_art)" "Rifle squad"}
{"vehic_supporter(usa_doc_art)" "Support crew"}
{"officers(usa_doc_art)" "Officer"}
{"gmc_art(art)" "GMC CCKW Heavy ammo truck"}
{"ammo_box_us_art(art)" "Heavy ammo crate"}
{"60mm_brandt_usa(art)" "M2 60mm mortar"}
{"81mm_brandt_usa(art)" "M1 81mm mortar"}
{"4_2_inch_mortar_m_2(art)" "M2 4.2-inch mortar"}
{"m8_howitzer(art)" "M8 howitzer"}
{"m2a1l(art)" "M2A1 L"}
{"m114(art)" "M114"}
{"longtom_155mm(art)" "Long tom"}
{"m115(art)" "M115"}
{"np_t19(art)" "T19"}
{"m7(art)" "M7 Priest"}
{"m12gmc(art)" "M12 GMC"}
{"m4a3c(art)" "M4A3 sherman calliope"}

;combined arms doctrine
{"riflemans(usa_doc_ca)" "Rifle squad"}
{"riflemans_bar(usa_doc_ca)" "Heavy Rifle squad"}
{"vehic_supporter(usa_doc_ca)" "Support crew"}
{"tankmans(usa_doc_ca)" "Tank crew"}
{"gmc_art(ca)" "GMC CCKW Heavy ammo truck"}
{"ammo_box_us_inf(ca)" "Infantry ammo crate"}
{"ammo_box_us_art(ca)" "Heavy ammo crate"}
{"30_browning_m1919a4(ca)" ".30cal Browning M1919A4 tripod"}
{"50_browning_m1919a4(ca)" ".50cal Browning M2HB tripod"}
{"60mm_brandt_usa(ca)" "M2 60mm mortar"}
{"81mm_brandt_usa(ca)" "M1 81mm mortar"}
{"m3cannon(ca)" "M3 AT gun"}
{"m1_57mm(ca)" "M1 AT gun"}
{"m20(ca)" "M20"}
{"m5a1(ca)" "M5A1 stuart"}
{"m4a1(ca)" "M4A1 sherman"}
{"m4a3_75(ca)" "M4A3 sherman"}

;defensive doctrine
{"riflemans(usa_doc_d)" "Rifle squad"}
{"vehic_supporter(usa_doc_d)" "Support crew"}
{"ap_miners(usa_doc_d)" "AP mine infantry"}
{"at_miners(usa_doc_d)" "AT mine infantry"}
{"sappers(usa_doc_d)" "Mine disposal infantry"}
{"mg2(usa_doc_d)" "Machine gunner"}
{"gmc_art(d)" "GMC CCKW Heavy ammo truck"}
{"gmc_eng(d)" "GMC CCKW Engineering truck"}
{"ammo_box_us_inf(d)" "Infantry ammo crate"}
{"ammo_box_us_art(d)" "Heavy ammo crate"}
{"ammo_box_us_special(d)" "Special ammo crate"}
{"30_browning_m1919a4(d)" ".30cal Browning M1919A4 tripod"}
{"50_browning_m1919a4(d)" ".50cal Browning M2HB tripod"}
{"60mm_brandt_usa(d)" "M2 60mm mortar"}
{"81mm_brandt_usa(d)" "M1 81mm mortar"}
{"4_2_inch_mortar_m_2(d)" "M2 4.2-inch mortar"}
{"maxson(d)" "Maxson"}
{"bofors(d)" "Bofors"}
{"m3cannon(d)" "M3 AT gun"}
{"m1_57mm(d)" "M1 AT gun"}
{"np_m5cannon(d)" "M5 AT gun"}
{"m36(d)" "90mm GMC M36"}

;elite troops doctrine
{"stormtroopers(usa_doc_et)" "Ranger squad"}
{"stormtroopers_heavy(usa_doc_et)" "Heavy Ranger squad"}
{"stormtroopers_assault(usa_doc_et)" "Assault Ranger squad"}
{"tankmans(usa_doc_et)" "Tank crew"}
{"vet_tankmans(usa_doc_et)" "Veteran Tank crew"}
{"gmc_art(et)" "GMC CCKW Heavy ammo truck"}
{"m4a3e8(et)" "M4A3E8(76)W sherman"}
{"m4a3e8_vet(et)" "Veteran M4A3E8(76)W sherman"}
{"m4a3e8_fury(et)" "M4A3E8(76)W sherman 'Fury'"}
{"m4a3e2_jumbo_76(et)" "M4A3E2(76)W Jumbo"}
{"m4a3e2_jumbo_76_elite(et)" "Elite M4A3E2(76)W Jumbo"}

;heavy support doctrine
{"riflemans(usa_doc_hs)" "Rifle squad"}
{"riflemans_bar(usa_doc_hs)" "Heavy Rifle squad"}
{"tankmans(usa_doc_hs)" "Tank crew"}
{"gmc_art(hs)" "GMC CCKW Heavy ammo truck"}
{"bofors(hs)" "Bofors"}
{"m12gmc(hs)" "M12 GMC"}
{"m16(hs)" "M16"}
{"m4a3_75(hs)" "M4A3 sherman"}
{"m4a3_105(hs)" "M4A3 105mm sherman"}
{"m26_pershing(hs)" "M26 Pershing"}

;infantry doctrine
{"riflemans(usa_doc_i)" "Rifle squad"}
{"riflemans_bar(usa_doc_i)" "Heavy Rifle squad"}
{"specialinf(usa_doc_i)" "Marine squad"}
{"stormtroopers_heavy(usa_doc_i)" "Heavy Ranger squad"}
{"devils_brigade(usa_doc_i)" "Devils Brigade squad"}
{"vehic_supporter(usa_doc_i)" "Support crew"}
{"bazookers(usa_doc_i)" "Bazooka infantry"}
{"stormtrooper5(usa_doc_i)" "Ranger Bazooka infantry"}
{"stormtrooper_at(usa_doc_i)" "Ranger recoilless rifle infantry"}
{"snipers(usa_doc_i)" "Sniper"}
{"officers(usa_doc_i)" "Officer"}
{"np_willysmb(i)" "Willys MB"}
{"np_willys50(i)" "Armored Willys MB .50cal"}
{"np_willysat(i)" "Willys AT"}
{"m3_usa(i)" "M3 halftrack"}
{"m2halftrack(i)" "M2 halftrack"}
{"ammo_box_us_inf(i)" "Infantry ammo crate"}
{"ammo_box_us_art(i)" "Heavy ammo crate"}
{"30_browning_m1919a4(i)" ".30cal Browning M1919A4 tripod"}
{"50_browning_m1919a4(i)" ".50cal Browning M2HB tripod"}
{"60mm_brandt_usa(i)" "M2 60mm mortar"}
{"81mm_brandt_usa(i)" "M1 81mm mortar"}
{"m3cannon(i)" "M3 AT gun"}

;mechanized cavalry
{"recon(usa_doc_mc)" "Recon squad"}
{"recon_heavy(usa_doc_mc)" "Heavy Recon squad"}
{"tankmans(usa_doc_mc)" "Tank crew"}
{"officers(usa_doc_mc)" "Officer"}
{"np_willysmb(mc)" "Willys MB"}
{"np_willysmb_50(mc)" "Willys MB .50cal"}
{"np_willysat(mc)" "Willys AT"}
{"m3_usa(mc)" "M3 halftrack"}
{"m2halftrack(mc)" "M2 halftrack"}
{"gmc_art(mc)" "GMC CCKW Heavy ammo truck"}
{"np_m15a1(mc)" "M15A1"}
{"m20(mc)" "M20"}
{"m16(mc)" "M16"}
{"m8grayhound(mc)" "M8 grayhound"}
{"m3stuart_early(mc)" "M3 stuart"}
{"m5a1(mc)" "M5A1 stuart"}
{"m8(mc)" "M8 scott"}
{"m24(mc)" "M24 Chaffee"}

;paratrooper doctrine
{"pathfinders(usa_doc_para)" "Pathfinder squad"}
{"elites(usa_doc_para)" "Airborne squad"}
{"elites_44_drop(usa_doc_para)" "Paradropped Airborne squad"}
{"elite_101st(usa_doc_para)" "101st Airborne squad"}
{"elite_101st_drop(usa_doc_para)" "Paradropped 101st Airborne squad"}
{"elite_101st_special(usa_doc_para)" "101st Airborne squad (special ability)"}
{"elite_101st_drop_special(usa_doc_para)" "Paradropped 101st Airborne squad (special ability)"}
{"elite_101st_bazooker(usa_doc_para)" "101st Airborne bazooka infantry"}
{"elite_sniper(usa_doc_para)" "Airborne sniper"}
{"para_supporter(usa_doc_para)" "101st Airborne support infantry"}
{"m1_57mm_drop(usa_doc_para)" "Paradropped M1 AT gun"}
{"np_willysmb(para)" "Willys MB"}
{"ammo_box_us_inf(para)" "Infantry ammo crate"}
{"ammo_box_us_art(para)" "Heavy ammo crate"}
{"30_browning_m1919a4(para)" ".30cal Browning M1919A4 tripod"}
{"50_browning_m1919a4(para)" ".50cal Browning M2HB tripod"}
{"60mm_brandt_usa(para)" "M2 60mm mortar"}
{"81mm_brandt_usa(para)" "M1 81mm mortar"}
{"m8_howitzer(para)" "M8 howitzer"}
{"m1_57mm(para)" "M1 AT gun"}
{"m8grayhound(para)" "M8 grayhound"}
{"m5a1(para)" "M5A1 stuart"}
{"m8(para)" "M8 scott"}

;tank assault doctrine
{"riflemans(usa_doc_ta)" "Armored Rifle squad"}
{"riflemans_btr(usa_doc_ta)" "Mechanized Armored Rifle squad"}
{"tankmans(usa_doc_ta)" "Tank crew"}
{"officers(usa_doc_ta)" "Armor Officer"}
{"gmc_art(ta)" "GMC CCKW Heavy ammo truck"}
{"m4a3c(ta)" "M4A3 sherman calliope"}
{"m19(ta)" "M19"}
{"m4a3_75(ta)" "M4A3 sherman"}
{"m4a3_105(ta)" "M4A3 105mm sherman"}
{"m4a3_zippo(ta)" "M4A3 sherman zippo"}
{"m4a3e2_jumbo(ta)" "M4A3E2 jumbo"}

;tank destroyer doctrine
{"riflemans(usa_doc_td)" "Armored Rifle squad"}
{"tankmans(usa_doc_td)" "Tank crew"}
{"officers(usa_doc_td)" "Armor Officer"}
{"gmc_art(td)" "GMC CCKW Heavy ammo truck"}
{"np_t48(td)" "T48"}
{"m18(td)" "76mm GMC M18 Hellcat"}
{"m10(td)" "76mm GMC M10 Wolverine"}
{"m36(td)" "90mm GMC M36 Slugger"}
{"m36b1(td)" "90mm GMC M36B1 Jackson"}











