	{level "lvl_1"		;little to no training
		{stand
			{accuracy 0.30}
		}
		{squat
			{accuracy 0.45}
		}
		{crawl
			{accuracy 0.55}
		}
		{cover
			{accuracy 0.60}
		}
	}
	{level "lvl_2"		;3 or less months
		{stand
			{accuracy 0.40}
		}
		{squat
			{accuracy 0.60}
		}
		{crawl
			{accuracy 0.70}
		}
		{cover
			{accuracy 0.75}
		}
	}
	{level "lvl_3"		;3-4 months
		{stand
			{accuracy 0.50}
		}
		{squat
			{accuracy 0.70}
		}
		{crawl
			{accuracy 0.80}
		}
		{cover
			{accuracy 0.85}
		}
	}
	{level "lvl_4"		;4-6 months
		{stand
			{accuracy 0.60}
		}
		{squat
			{accuracy 0.80}
		}
		{crawl
			{accuracy 0.90}
		}
		{cover
			{accuracy 0.95}
		}
	}
	{level "lvl_5"		;4-6 months +
		{stand
			{accuracy 0.75}
		}
		{squat
			{accuracy 0.95}
		}
		{crawl
			{accuracy 1.05}
		}
		{cover
			{accuracy 1.10}
		}
	}
	{level "lvl_6"		;veteran or highly trained light infantry
		{stand
			{accuracy 0.90}
		}
		{squat
			{accuracy 1.10}
		}
		{crawl
			{accuracy 1.20}
		}
		{cover
			{accuracy 1.25}
		}
	}
	{level "lvl_7"		;army rangers
		{stand
			{accuracy 1.00}
		}
		{squat
			{accuracy 1.21}
		}
		{crawl
			{accuracy 1.31}
		}
		{cover
			{accuracy 1.36}
		}
	}
	{level "lvl_8"		;green berets
		{stand
			{accuracy 1.10}
		}
		{squat
			{accuracy 1.35}
		}
		{crawl
			{accuracy 1.45}
		}
		{cover
			{accuracy 1.50}
		}
	}
	{level "lvl_9"		;gru spetsnaz
		{stand
			{accuracy 1.30}
		}
		{squat
			{accuracy 1.50}
		}
		{crawl
			{accuracy 1.60}
		}
		{cover
			{accuracy 1.65}
		}
	}
	{level "lvl_10"		;delta force
		{stand
			{accuracy 1.50}
		}
		{squat
			{accuracy 1.70}
		}
		{crawl
			{accuracy 1.80}
		}
		{cover
			{accuracy 1.90}
		}
	}